

INSERT INTO product (title, price, category, description, image, rating)
VALUES ('Puma', 109.95, 'Your perfect shoes for everyday use and walks in the forest', 'shoes',
        'https://i.ibb.co/F00LzVc/aqua-lavender-casuals.jpg', 3),
       ('Mens Casual Premium Slim Fit T-Shirts', 122.3,
        'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing.',
        'clothing', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 4.),
       ('Mens Cotton Jacket', 55.99,
        'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors.',
        'clothing', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', '4.7'),
       ('Mens Casual Slim Fit', 15.99,
        'The color could be slightly different between on the screen and in practice.  Please note that body builds vary by person, therefore, detailed size information should be reviewed.',
        'clothing', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 2.1),
       ('Asics Mens Running Shoe', 600,
        'Soft, light-weight for off-road and pavement running. Strong support for pronated athletes.', 'shoes',
        'https://i.ibb.co/3WfYXBc/asics-white-running-show.jpg', 4.6),
       ('Converse light-blue casuals', 168,
        'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
        'shoes', 'https://i.ibb.co/Y85qjyR/converse-light-blue-casuals.jpg', 3.9),
       ('Marine Mens Athletics', 199.99, 'Classic mens training shoe. Perfect for training or for casual events',
        'mens shoes', 'https://i.ibb.co/JCyB1X6/marine-green-athletic-shoe.jpg', 3),
       ('Nike Black White Tick Mens Shoe', 210.99,
        'Classic, causal Nike support for all activities', 'mens shoes',
        'https://i.ibb.co/tMQwJSV/nike-black-white-swoosh-casual.jpg', 1.9),
       ('Nike Cherry Blossom',64,
         'Stylish classics for casual and athletic activities. LIMITED STOCK!', 'mens shoes','https://i.ibb.co/BK8wqVD/nike-cherry-blossom.jpg',
         3.3),
       ('Nike Runners Shoe - Red', 200,
        'Soft, light-weight for off-road and pavement running. Strong support for pronated athletes.', 'shoes',
        'https://i.ibb.co/ZBy31t4/red-nike.jpg', 4.6),
       ('White Casuals', 200,
        'Soft, light-weight for off-road and pavement running. Strong support for pronated athletes.', 'shoes',
        'https://i.ibb.co/8DcDjSv/white-casual-shoe.jpg', 4.6),
       ('Fila Casuals', 600,
        'Soft, light-weight for off-road and pavement running. Strong support for pronated athletes.', 'shoes',
        'https://i.ibb.co/gPcxJ1y/white-fila.jpg', 4.6);
